name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Make sure commit messages follow the conventional commits convention:
  # https://www.conventionalcommits.org
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Docs
        run: |
          npm run typedoc:md
          npm run typedoc:html
      - name: Test
        run: npm test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: release
      # Pages
      url: ${{ steps.deployment.outputs.url }}
    concurrency: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      # Pages
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Docs
        run: |
          npm run typedoc:md
          npm run typedoc:html
      - name: Release
        if: github.ref_name == 'main'
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy Documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
